#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr  3 09:57:23 2019

@author: ayeshabhatnagar
"""

VALID_CHARACTERS_IP6 = 'ABCDEFabcdef:0123456789'
VALID_CHARACTERS_IP4 = '.0123456789'


def valid_ip6(address):
    address_list = address.split(':')
    return (
        len(address_list) == 8
        and all(len(current) <= 4 for current in address_list)
        and all(current in VALID_CHARACTERS_IP6 for current in address)
    )
    
def valid_ip4(address):
    address_list = address.split('.')
    return(
            all(int(current) <= 256 for current in address_list)
        and all(current in VALID_CHARACTERS_IP4 for current in address)
            )
    
#sample inputs for testing ipv6 .. copy these
    # 2001:0db8:85a3:0000:0000:8a2e:0370:7334
#sample inputs for testing ipv4 .. copy these
    # 125.230.120.1
# 256.256.256.256   
if __name__ == '__main__':
    address = input('Please enter an IP address: ')

    if valid_ip6(address):
        print('Valid IPv6 address.')
    if valid_ip4(address):
        print('Valid IPv4 address')
    if not valid_ip6(address):
        print('It is not a valid IPv6 address.')
    if not valid_ip4(address):
        print('It is not a valid IPv4 address.')    
        